Use SLCMandPLACEMENTF;
create table Slogin(Regno varchar(20) primary key,password varchar(20));
create table Studentinfo( Regno varchar(20) ,name varchar(20) ,year varchar(10), branch varchar(20),dateofbirth varchar(20),gender varchar(20),mobileno varchar(20),email varchar(50),nationality varchar(20),Semester int,primary key(Regno,Semester));
Create table CourseDetails(subjectcode varchar(10) primary key,subjectname varchar(30),classification varchar(20),type varchar(10),Semester int,branch varchar(20),credit int);
Create Table Takes (Sno int not null AUTO_INCREMENT,Regno varchar(20),subjectcode varchar(10),primary key(Sno,Regno,subjectcode),foreign key(Regno) references Studentinfo(Regno),foreign key(subjectcode) references CourseDetails(subjectcode));
create table Teacher(Tid varchar(20) primary key ,Tname varchar(20),Branch varchar(20),Salary int);
create table Tlogin(ID varchar(20) primary key,password varchar(20));
create table Attendance(Sno int not null AUTO_INCREMENT,Regno varchar(20),subjectcode varchar(10),TotalClasses int,DaysPresent int,DaysAbsent int,primary key (Sno,Regno,subjectcode),foreign key (Regno) references Studentinfo(Regno),foreign key(subjectcode) references CourseDetails(subjectcode));
create table Marks(Sno int not null AUTO_INCREMENT,Regno varchar(20),subjectcode varchar(10),TotalMarks int,MarksObtained int,Type Varchar(20),CGPA float,primary key (Sno,Regno,subjectcode),foreign key (Regno) references Studentinfo(Regno),foreign key(subjectcode) references CourseDetails(subjectcode));
Create Table Teaches (Sno int not null AUTO_INCREMENT,Tid varchar(20),subjectcode varchar(10),primary key(Sno,Tid,subjectcode),foreign key(Tid) references Teacher(Tid),foreign key(subjectcode) references CourseDetails(subjectcode));
Create table Clogin(Username Varchar(20) Primary key,Password varchar(20));
Create table CompanyDetails(Companyname varchar(30) primary key,jobprofile varchar(50),package int);
Create table Apply(APPid int not null AUTO_INCREMENT primary key,Regno varchar(20),Companyname varchar(50),foreign key(Regno) references studentinfo(Regno),Foreign key(Companyname) references CompanyDetails(Companyname));
Create table OnlineTest(Companyname varchar(20),Question varchar(100),Answer varchar(50),primary key(Companyname,Question),Foreign key(Companyname) references CompanyDetails(Companyname));
Create table PlacementStatus(APPid int,Status varchar(20),primary key(Appid,Status),Foreign key(APPid) references Apply(Appid));
Create table Financials(Regno varchar(20),Paymentno varchar(20),PaymentDetails varchar(50),Fees int,Status varchar(10),primary key(Regno,Paymentno));
Create table Grades(Regno varchar(20),Semester int,GPA Float,primary key(Regno,Semester),Foreign key(Regno) references Studentinfo(Regno));
Create table Selected(APPid varchar(20) ,Companyname varchar(50),Status varchar(20), Primary key(Companyname,Appid,Status),Foreign key(Companyname) references CompanyDetails(Companyname));
insert into Marks(Regno,subjectcode,TotalMarks,MarksObtained,Type,CGPA) values('170953280','ICT2100',15,14,'Sessional1',9);
insert into Marks(Regno,subjectcode,TotalMarks,MarksObtained,Type,CGPA) values('170953281','ICT2100',15,10,'Sessional1',7.8);
insert into Attendance(Regno,subjectcode ,TotalClasses ,DaysPresent ,DaysAbsent) values('170953280','ICT2100',20,19,1);
insert into takes(Regno,subjectcode) values('170953280','ICT2100');
insert into Teaches(Tid,subjectcode) values('CCET3','ICT2100');
select Marks.subjectcode,subjectname,Marks.Type,TotalMarks,MarksObtained from CourseDetails ,Marks where CourseDetails.subjectcode=Marks.subjectcode and Semester=5 and branch='CCE' and Regno='170953280';
select Attendance.subjectcode,subjectname,TotalClasses,DaysPresent,DaysAbsent from CourseDetails  , Attendance where CourseDetails.subjectcode=Attendance.subjectcode and Semester=5 and branch='CCE' and Regno='170953280';